// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0qBExjzCOq2318lRBpEw3mA89eP1huwk',
    appId: '1:414543950952:web:1e96667f70dc1ba45037dd',
    messagingSenderId: '414543950952',
    projectId: 'flutteruserapp-d80a5',
    authDomain: 'flutteruserapp-d80a5.firebaseapp.com',
    storageBucket: 'flutteruserapp-d80a5.firebasestorage.app',
    measurementId: 'G-30D7QF7J7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRVeGe0oc9IwoVAwu0YiLLrCIn3bh-lkY',
    appId: '1:414543950952:android:27b98d4e1a9531b35037dd',
    messagingSenderId: '414543950952',
    projectId: 'flutteruserapp-d80a5',
    storageBucket: 'flutteruserapp-d80a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD82XsMEbMOIlgDOvZQ0e12ZFK_fFKQMeg',
    appId: '1:414543950952:ios:bc5550ce2d5979ca5037dd',
    messagingSenderId: '414543950952',
    projectId: 'flutteruserapp-d80a5',
    storageBucket: 'flutteruserapp-d80a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAdminapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD82XsMEbMOIlgDOvZQ0e12ZFK_fFKQMeg',
    appId: '1:414543950952:ios:bc5550ce2d5979ca5037dd',
    messagingSenderId: '414543950952',
    projectId: 'flutteruserapp-d80a5',
    storageBucket: 'flutteruserapp-d80a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAdminapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0qBExjzCOq2318lRBpEw3mA89eP1huwk',
    appId: '1:414543950952:web:5bea5a0717a9904a5037dd',
    messagingSenderId: '414543950952',
    projectId: 'flutteruserapp-d80a5',
    authDomain: 'flutteruserapp-d80a5.firebaseapp.com',
    storageBucket: 'flutteruserapp-d80a5.firebasestorage.app',
    measurementId: 'G-SE4KMJ9BFS',
  );
}
